# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20171118_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactory',
            name='support_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='支持电话'),
        ),
    ]
