# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-10 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
